export const INSTITUTES = [
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT (ISM) Dhanbad",
  "IIT Indore",
  "IIT Ropar",
  "IIT Bhubaneswar",
  "IIT Gandhinagar",
  "IIT Jodhpur",
  "IIT Patna",
  "IIT Mandi",
  "IIT Palakkad",
  "IIT Tirupati",
  "NIT Trichy",
  "NIT Surathkal",
  "NIT Warangal",
  "NIT Calicut",
  "NIT Rourkela",
  "MNNIT Allahabad",
  "NIT Durgapur",
  "NIT Kurukshetra",
  "VNIT Nagpur",
  "SVNIT Surat",
  "NIT Jaipur",
  "NIT Jalandhar",
  "NIT Silchar",
  "NIT Hamirpur",
];

export const DEPARTMENTS = [
    "Computer Science and Engineering",
    "Electronics and Communication Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Biotechnology",
    "Aerospace Engineering",
    "Metallurgical and Materials Engineering",
    "Materials Science and Engineering",
    "Engineering Physics",
    "Physics",
    "Chemistry",
    "Mathematics",
    "Humanities and Social Sciences",
    "Management Studies",
];